name: learning_flutter
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_screenutil: ^4.0.3+3
  provider: ^4.3.2+3
  firebase_auth: ^0.20.0+1
  google_sign_in: ^4.5.9
  firebase_core: ^0.7.0
  shared_preferences: ^0.5.12+4
  email_validator: ^1.0.6
  flushbar: ^1.10.4
  # flutter_facebook_login: ^3.0.0
  cloud_firestore: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/